config:
  gcp:project: kalilos-connector-dev
  gcp:region: us-central1
  kalilos:scheduler-cron: '*/30 * * * *'
  kalilos:scheduler-timezone: America/New_York
  kalilos:gdrive-root-folder: Kalilos Reports
  kalilos:gdrive-root-folder-id: 0AMwE_D4Cl8OUUk9PVA
  kalilos:frontend-url: https://kalilos-connector.vercel.app
  kalilos:supabase-url: https://ckrbkeljuevemzclcpod.supabase.co
  kalilos:supabase-db-url:
    secure: v1:kphLbv0X+UYxLXP9:uedRzuObhwxsS1NFDmH3o4qNI2XGMXf6WrvdeaxjxY7utmQrrAbBfzr+uRKebnD6cf0YjGYh7q1Q6SknFlC1iK0IcNjuuCwtOljrm36i68m9WSnWOGA6IGFoKX8MeIPilmtzVtsr
  kalilos:api-key:
    secure: v1:+RRk3cVWCjZHdf3B:91S1varJVpSkP38gjPsW8K+TH7D8j3Mki4mNkbZFykPtIL/E9Z0ZQCHoxxPOKVq1UfOamlw2LX8=
  kalilos:mcp-api-key:
    secure: v1:NYMGhoMQYkA7n+yh:qYRfYs5em/7SI/KyzRKsEGPsm2zbYBhjySqk1XOIg8MmFbSv6ho1fCSOxcK4HnCusR9bgi1UDnk=
encryptionsalt: v1:nTohlkOlwzg=:v1:3KUpiw23DzngV9cN:TiGxe4Vt8lbPyil9eaRCTshhGBwf2Q==
