encryptionsalt: v1:Gmg6BKBW3Jg=:v1:nzRJ89Z1j2aKP0rJ:oAYfegXpkMYo01vFq+9bPN9sWrmPoQ==
config:
  gcp:project: kalilos-connector-staging
  gcp:region: us-central1
  kalilos:scheduler-cron: '*/30 * * * *'
  kalilos:scheduler-timezone: America/New_York
  kalilos:gdrive-root-folder: Kalilos Reports [STAGING]
  kalilos:gdrive-root-folder-id: 0AMwE_D4Cl8OUUk9PVA
  kalilos:api-key:
    secure: v1:2AXdN7ZBVtwePJvg:c47KgN6yk/yGBIf2u9T/0y2nG+3Tcm+ZvlAnD2244haB+Qgsb9K33wbXZ+IY70ahAmSVR2fraeP3FXCc7cGm5hqz8/KTune94fSEOhIIh/c=
  kalilos:frontend-url: https://kalilos-connector-staging.web.app
  kalilos:mcp-api-key:
    secure: v1:WGFKxIsF1QYPhByH:bj1jeNC4a/fPmDofceYhOCYHkMhul/ZzCKv3Rkg00rSXJWeIq57+Q02Cj8jOKA1z8jvQIIJYm0HDPgAiAnAPF9GUsTju8u1zSWtYg7gv7XM=