#!/usr/bin/env python3
"""Create (or update) test schedules in Supabase that cover every report type.

Reports are grouped by their timeframe requirements:
  - "daily"   → yesterday strategy (most SP API reports, all Ads reports)
  - "monthly" → last_calendar_month strategy (Brand Analytics that need WEEK/MONTH)
  - "skip"    → non-requestable reports (settlement reports)

Each group becomes one test schedule per API source (sp_api / ads_api).

Usage:
    python tests/seed_report_test_schedules.py [--client CLIENT_ID] [--dry-run]

Re-running the script is idempotent — it deletes any existing "test-report-*"
schedules and recreates them from scratch based on the current report registry.
"""

from __future__ import annotations

import argparse
import os
import sys

# Allow imports from functions/
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "functions"))

from shared.ads_report_config import ADS_REPORT_TYPES
from shared.api_operations import API_OPERATIONS
from shared.db import create_schedule, delete_schedule, list_schedules
from shared.removed_reports import REMOVED_SP_REPORT_TYPES
from shared.vendor_reports import VENDOR_SP_REPORT_TYPES

# ---------------------------------------------------------------------------
# Report classification
# ---------------------------------------------------------------------------

# Non-requestable: settlement reports are auto-generated by Amazon, and the
# Subscribe & Save reports were permanently removed from the SP-API (see
# shared.removed_reports). Both are excluded from the generated test schedules.
_NON_REQUESTABLE = {
    "GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2",
    "GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE",
    *REMOVED_SP_REPORT_TYPES,
}

_MONTHLY_ONLY_SP = {
    "GET_BRAND_ANALYTICS_MARKET_BASKET_REPORT",
    "GET_BRAND_ANALYTICS_REPEAT_PURCHASE_REPORT",
    "GET_BRAND_ANALYTICS_ALTERNATE_PURCHASE_REPORT",
    "GET_BRAND_ANALYTICS_SEARCH_QUERY_PERFORMANCE_REPORT",
    "GET_BRAND_ANALYTICS_SEARCH_CATALOG_PERFORMANCE_REPORT",
}

ALL_SP_REPORT_TYPES = [
    "GET_FLAT_FILE_OPEN_LISTINGS_DATA",
    "GET_MERCHANT_LISTINGS_ALL_DATA",
    "GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL",
    "GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL",
    "GET_SALES_AND_TRAFFIC_REPORT",
    "GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA",
    "GET_FBA_MYI_ALL_INVENTORY_DATA",
    "GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA",
    "GET_AFN_INVENTORY_DATA",
    "GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT",
    "GET_STRANDED_INVENTORY_UI_DATA",
    "GET_LEDGER_SUMMARY_VIEW_DATA",
    "GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2",
    "GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL",
    "GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE",
    "GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA",
    "GET_FBA_FULFILLMENT_REMOVAL_SHIPMENT_DETAIL_DATA",
    "GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT",
    "GET_BRAND_ANALYTICS_MARKET_BASKET_REPORT",
    "GET_BRAND_ANALYTICS_REPEAT_PURCHASE_REPORT",
    "GET_BRAND_ANALYTICS_SEARCH_QUERY_PERFORMANCE_REPORT",
    "GET_BRAND_ANALYTICS_SEARCH_CATALOG_PERFORMANCE_REPORT",
    "GET_MERCHANT_LISTINGS_DATA",
    "GET_FBA_INVENTORY_PLANNING_DATA",
]

ALL_ADS_REPORT_TYPES = list(ADS_REPORT_TYPES.keys())

# Vendor (1P) reports — require a Vendor Central account, so they live in their
# own schedule (seeded only when a --vendor-client is supplied).
ALL_VENDOR_REPORT_TYPES = sorted(VENDOR_SP_REPORT_TYPES)

# Synchronous API operations (Replenishment / Subscribe & Save). These take the
# fetch_api path rather than the create-report pipeline.
ALL_API_OPERATIONS = list(API_OPERATIONS.keys())


def classify_sp_reports() -> dict[str, list[str]]:
    groups: dict[str, list[str]] = {"daily": [], "monthly": [], "skip": []}
    for rt in ALL_SP_REPORT_TYPES:
        if rt in _NON_REQUESTABLE:
            groups["skip"].append(rt)
        elif rt in _MONTHLY_ONLY_SP:
            groups["monthly"].append(rt)
        else:
            groups["daily"].append(rt)
    return groups


# ---------------------------------------------------------------------------
# Schedule builders
# ---------------------------------------------------------------------------

def _base_schedule(
    name: str,
    client_ids: list[str],
    api_source: str,
    report_types: list[str],
    marketplace: str,
    timeframe: dict,
    folder_name: str,
) -> dict:
    return {
        "name": name,
        "client_ids": client_ids,
        "api_source": api_source,
        "report_types": report_types,
        "marketplaces": [marketplace],
        "frequency": "daily",
        "schedule_config": {"type": "daily", "time": "06:00"},
        "timeframe": timeframe,
        "folder_name": folder_name,
        "subfolder_strategy": "date",
        "reconciliation_days": [],
        "report_params": {},
        "is_active": False,
    }


def build_test_schedules(
    client_ids: list[str],
    marketplace: str = "US",
    vendor_client_ids: list[str] | None = None,
) -> list[dict]:
    sp = classify_sp_reports()
    schedules: list[dict] = []

    if sp["daily"]:
        schedules.append(_base_schedule(
            name="Test: SP Daily Reports",
            client_ids=client_ids,
            api_source="sp_api",
            report_types=sp["daily"],
            marketplace=marketplace,
            timeframe={"strategy": "yesterday"},
            folder_name="test-reports-daily",
        ))

    if sp["monthly"]:
        schedules.append(_base_schedule(
            name="Test: SP Monthly Reports (Brand Analytics)",
            client_ids=client_ids,
            api_source="sp_api",
            report_types=sp["monthly"],
            marketplace=marketplace,
            timeframe={"strategy": "last_calendar_month"},
            folder_name="test-reports-monthly",
        ))

    if ALL_ADS_REPORT_TYPES:
        schedules.append(_base_schedule(
            name="Test: Ads Daily Reports",
            client_ids=client_ids,
            api_source="ads_api",
            report_types=ALL_ADS_REPORT_TYPES,
            marketplace=marketplace,
            timeframe={"strategy": "yesterday"},
            folder_name="test-reports-ads",
        ))

    if vendor_client_ids and ALL_VENDOR_REPORT_TYPES:
        schedules.append(_base_schedule(
            name="Test: Vendor (1P) Reports",
            client_ids=vendor_client_ids,
            api_source="sp_api",
            report_types=ALL_VENDOR_REPORT_TYPES,
            marketplace=marketplace,
            timeframe={"strategy": "yesterday"},
            folder_name="test-reports-vendor",
        ))

    if ALL_API_OPERATIONS:
        # Synchronous Replenishment / S&S operations (fetch_api path). A weekly
        # window suits the Subscribe & Save metrics aggregation.
        schedules.append(_base_schedule(
            name="Test: Subscribe & Save (Replenishment API)",
            client_ids=client_ids,
            api_source="sp_api",
            report_types=ALL_API_OPERATIONS,
            marketplace=marketplace,
            timeframe={"strategy": "last_calendar_week"},
            folder_name="test-reports-sns",
        ))

    return schedules


# ---------------------------------------------------------------------------
# Supabase operations
# ---------------------------------------------------------------------------

TEST_SCHEDULE_PREFIX = "test-report-"


def sync_to_supabase(
    schedules: list[dict],
    dry_run: bool = False,
) -> None:
    existing = [
        s for s in list_schedules()
        if (s.get("folder_name") or "").startswith("test-reports-")
    ]

    if existing:
        print(f"  Removing {len(existing)} existing test schedule(s)...")
        if not dry_run:
            for s in existing:
                delete_schedule(s["id"])

    for sched in schedules:
        report_count = len(sched["report_types"])
        print(f"  + {sched['name']}  ({report_count} report types, {sched['timeframe']['strategy']})")
        if not dry_run:
            create_schedule(sched)

    skipped = classify_sp_reports()["skip"]
    if skipped:
        print(f"\n  Skipped (non-requestable): {', '.join(skipped)}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Seed Supabase with test schedules covering all report types",
    )
    parser.add_argument(
        "--client",
        default="Betallic",
        help="Client ID to use (must have SP + Ads credentials)",
    )
    parser.add_argument(
        "--vendor-client",
        default=None,
        help="Optional Vendor (1P) client ID to seed a vendor-reports test schedule",
    )
    parser.add_argument(
        "--marketplace",
        default="US",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print without writing")
    args = parser.parse_args()

    if not os.environ.get("SUPABASE_DB_URL"):
        print("Error: SUPABASE_DB_URL is not set.", file=sys.stderr)
        sys.exit(1)

    print(f"Client:      {args.client}")
    print(f"Marketplace: {args.marketplace}")
    print()

    schedules = build_test_schedules(
        client_ids=[args.client],
        marketplace=args.marketplace,
        vendor_client_ids=[args.vendor_client] if args.vendor_client else None,
    )

    total_reports = sum(len(s["report_types"]) for s in schedules)
    print(f"Creating {len(schedules)} test schedule(s) covering {total_reports} report types:\n")

    sync_to_supabase(schedules, dry_run=args.dry_run)

    if args.dry_run:
        print("\n  (dry run — no changes written)")
    else:
        print(f"\nDone. Schedules are created as INACTIVE — trigger via 'Run Now' in the UI.")


if __name__ == "__main__":
    main()
