"""Regression tests for create_report's Amazon-error humanization.

Bug: `_humanize_create_error` used to combine two unrelated conditions with
`or`:

    if report_type in _NON_REQUESTABLE_REPORTS or "not allowed at this time" in lower:

Amazon returns "not allowed at this time" for *any* report type when the
app is missing a Role or a role/reconnect change hasn't propagated yet —
it has nothing to do with settlement reports being auto-generated. Because
of the `or`, that generic rejection got mislabeled as the settlement-report
guard for every report type, e.g. telling a client to remove
GET_DATE_RANGE_FINANCIAL_TRANSACTION_DATA (a report that CAN be requested
on demand) from its schedule and "download settlements from Seller Central
instead" — which doesn't even apply to that report.

These tests pin the two conditions as independent branches.
"""

from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "functions"))

os.environ.setdefault("GCP_PROJECT", "test-project")
os.environ.setdefault("ENVIRONMENT", "staging")
os.environ.setdefault("WORKFLOW_NAME", "test-workflow")
os.environ.setdefault("WORKFLOW_LOCATION", "us-central1")


class TestHumanizeCreateError:
    def test_settlement_report_gets_settlement_message(self):
        from create_report.main import _humanize_create_error

        msg = _humanize_create_error(
            "some raw Amazon error", "GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2"
        )
        assert "auto-generated by Amazon" in msg
        assert "Seller Central" in msg

    def test_not_allowed_on_non_settlement_report_gets_role_message(self):
        """The exact regression: a non-settlement report rejected with Amazon's
        generic "not allowed at this time" must NOT be mislabeled as a
        settlement-report issue."""
        from create_report.main import _humanize_create_error

        msg = _humanize_create_error(
            "Bad Request: reportType is not allowed at this time",
            "GET_DATE_RANGE_FINANCIAL_TRANSACTION_DATA",
        )
        assert "auto-generated by Amazon" not in msg
        assert "Seller Central" not in msg
        assert "not allowed" in msg
        assert "Role" in msg

    def test_not_allowed_on_settlement_report_still_gets_settlement_message(self):
        """Belt and suspenders: if a settlement report *also* happens to error
        with "not allowed at this time", the settlement guidance still wins
        since it's the more specific/actionable guard."""
        from create_report.main import _humanize_create_error

        msg = _humanize_create_error(
            "reportType is not allowed at this time",
            "GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2",
        )
        assert "auto-generated by Amazon" in msg
