"""Kalilos MCP Server — agentic interface to the Amazon Reports Connector.

Exposes 15 tools for managing report schedules, triggering on-demand reports,
monitoring job status, and discovering Ads API profiles. Works across Cursor,
Claude Desktop, Claude.ai, Claude Code, and the Anthropic API.

Run locally:
    python server.py                     # HTTP on :8080
    MCP_TRANSPORT=stdio python server.py # stdio for Cursor/Claude Code

Deploy:
    Cloud Run via Dockerfile (uvicorn + ASGI)
"""

from __future__ import annotations

import os
from contextlib import asynccontextmanager

from fastmcp import FastMCP
from starlette.requests import Request
from starlette.responses import JSONResponse

from api_client import ApiError, KalilosApiClient
from auth import create_auth_provider

# ── HTTP client (shared across all tool calls) ──────────────────────────

api = KalilosApiClient()


@asynccontextmanager
async def lifespan(app: FastMCP):
    yield
    await api.close()


# ── Server ──────────────────────────────────────────────────────────────

mcp = FastMCP(
    "kalilos",
    instructions=(
        "Kalilos Amazon Reports Connector. Manage Amazon SP API and Ads API "
        "report schedules, trigger on-demand report downloads, and monitor "
        "job status. Reports are stored in Google Drive.\n\n"
        "Marketplaces: US, CA, MX, UK, DE, FR, IT, ES, AU.\n"
        "API sources: sp_api, ads_api, or both.\n"
        "Timeframe strategies: yesterday, today, last_n_days, rolling_window, "
        "last_calendar_week, last_calendar_month.\n\n"
        "Typical workflow: list_clients -> list_report_types -> "
        "create_schedule or request_report -> list_jobs to monitor."
    ),
    auth=create_auth_provider(),
    lifespan=lifespan,
)


# ── Health check (custom route, no auth) ────────────────────────────────


@mcp.custom_route("/health", methods=["GET"])
async def health(request: Request) -> JSONResponse:
    return JSONResponse({"status": "ok", "service": "kalilos-mcp"})


# ── Static catalog ──────────────────────────────────────────────────────

SP_REPORT_TYPES: list[dict] = [
    {"id": "GET_FLAT_FILE_OPEN_LISTINGS_DATA", "label": "Open Listings", "api": "sp_api", "category": "Listings"},
    {"id": "GET_MERCHANT_LISTINGS_ALL_DATA", "label": "All Listings", "api": "sp_api", "category": "Listings"},
    {"id": "GET_MERCHANT_LISTINGS_DATA", "label": "Active Listings", "api": "sp_api", "category": "Listings"},
    {"id": "GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL", "label": "Orders (by Order Date)", "api": "sp_api", "category": "Orders"},
    {"id": "GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL", "label": "Orders (by Last Update)", "api": "sp_api", "category": "Orders"},
    {"id": "GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL", "label": "Amazon Fulfilled Shipments", "api": "sp_api", "category": "Orders"},
    {"id": "GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA", "label": "FBA Inventory (Unsuppressed)", "api": "sp_api", "category": "FBA Inventory"},
    {"id": "GET_AFN_INVENTORY_DATA", "label": "AFN Inventory", "api": "sp_api", "category": "FBA Inventory"},
    {"id": "GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA", "label": "FBA Estimated Fees", "api": "sp_api", "category": "FBA Inventory"},
    {"id": "GET_FBA_MYI_ALL_INVENTORY_DATA", "label": "FBA Inventory (All)", "api": "sp_api", "category": "FBA Inventory"},
    {"id": "GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT", "label": "Restock Inventory Recommendations", "api": "sp_api", "category": "FBA Inventory"},
    {"id": "GET_STRANDED_INVENTORY_UI_DATA", "label": "Stranded Inventory", "api": "sp_api", "category": "FBA Inventory"},
    {"id": "GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE", "label": "FBM Returns", "api": "sp_api", "category": "Returns"},
    {"id": "GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA", "label": "FBA Returns", "api": "sp_api", "category": "Returns"},
    {"id": "GET_FBA_FULFILLMENT_REMOVAL_SHIPMENT_DETAIL_DATA", "label": "Removal Shipment Detail", "api": "sp_api", "category": "Returns"},
    {"id": "GET_LEDGER_SUMMARY_VIEW_DATA", "label": "Ledger Summary", "api": "sp_api", "category": "Financial"},
    {"id": "GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2", "label": "Settlement Report", "api": "sp_api", "category": "Financial", "note": "Auto-generated by Amazon — cannot be requested on demand"},
    {"id": "GET_SALES_AND_TRAFFIC_REPORT", "label": "Sales & Traffic", "api": "sp_api", "category": "Sales & Traffic", "note": "Requires Brand Registry"},
    {"id": "GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT", "label": "Search Terms", "api": "sp_api", "category": "Brand Analytics", "note": "Requires Brand Registry"},
    {"id": "GET_BRAND_ANALYTICS_MARKET_BASKET_REPORT", "label": "Market Basket", "api": "sp_api", "category": "Brand Analytics", "note": "Requires Brand Registry; only last_calendar_week or last_calendar_month"},
    {"id": "GET_BRAND_ANALYTICS_REPEAT_PURCHASE_REPORT", "label": "Repeat Purchase", "api": "sp_api", "category": "Brand Analytics", "note": "Requires Brand Registry; only last_calendar_week or last_calendar_month"},
    {"id": "GET_BRAND_ANALYTICS_SEARCH_QUERY_PERFORMANCE_REPORT", "label": "Search Query Performance", "api": "sp_api", "category": "Brand Analytics", "note": "Requires Brand Registry; only last_calendar_week or last_calendar_month"},
    {"id": "GET_BRAND_ANALYTICS_SEARCH_CATALOG_PERFORMANCE_REPORT", "label": "Search Catalog Performance", "api": "sp_api", "category": "Brand Analytics", "note": "Requires Brand Registry; only last_calendar_week or last_calendar_month"},
]

ADS_REPORT_TYPES: list[dict] = [
    {"id": "spCampaigns", "label": "SP Campaigns", "api": "ads_api", "category": "Sponsored Products"},
    {"id": "spSearchTerm", "label": "SP Search Term", "api": "ads_api", "category": "Sponsored Products"},
    {"id": "spTargeting", "label": "SP Targeting", "api": "ads_api", "category": "Sponsored Products"},
    {"id": "spAdvertisedProduct", "label": "SP Advertised Product", "api": "ads_api", "category": "Sponsored Products"},
    {"id": "sbCampaigns", "label": "SB Campaigns", "api": "ads_api", "category": "Sponsored Brands"},
    {"id": "sbSearchTerm", "label": "SB Search Term", "api": "ads_api", "category": "Sponsored Brands"},
    {"id": "sdCampaigns", "label": "SD Campaigns", "api": "ads_api", "category": "Sponsored Display"},
    {"id": "sdTargeting", "label": "SD Targeting", "api": "ads_api", "category": "Sponsored Display"},
    {"id": "sdAdvertisedProduct", "label": "SD Advertised Product", "api": "ads_api", "category": "Sponsored Display"},
    {"id": "spPlacement", "label": "SP Placement", "api": "ads_api", "category": "Sponsored Products"},
]

MARKETPLACES = ["US", "CA", "MX", "UK", "DE", "FR", "IT", "ES", "AU"]


# ── Helpers ─────────────────────────────────────────────────────────────


def _err(exc: ApiError) -> dict:
    return {"error": True, "code": exc.code, "message": str(exc)}


# ── Read-only tools ─────────────────────────────────────────────────────


@mcp.tool(annotations={"readOnlyHint": True})
async def list_clients(active_only: bool = False) -> list[dict] | dict:
    """List all configured Amazon seller clients.

    Each client represents an Amazon seller account with SP API and/or
    Ads API credentials. Returns id, name, marketplaces, and connection
    status. Use this to discover valid client_ids.
    """
    try:
        return await api.list_clients(active=active_only)
    except ApiError as e:
        return _err(e)


@mcp.tool(annotations={"readOnlyHint": True})
async def get_client(client_id: str) -> dict:
    """Get details for a specific client.

    Returns name, active marketplaces, SP API / Ads API connection status,
    and timestamps.
    """
    try:
        return await api.get_client(client_id)
    except ApiError as e:
        return _err(e)


@mcp.tool(annotations={"readOnlyHint": True})
async def list_schedules(
    client_id: str | None = None,
    active_only: bool = False,
) -> list[dict] | dict:
    """List report schedules, optionally filtered.

    Schedules define recurring report downloads — which clients,
    marketplaces, report types, frequency, and timeframe strategy.
    """
    try:
        return await api.list_schedules(client_id=client_id, active=active_only)
    except ApiError as e:
        return _err(e)


@mcp.tool(annotations={"readOnlyHint": True})
async def get_schedule(schedule_id: str) -> dict:
    """Get full configuration of a specific schedule.

    Returns client_ids, marketplaces, report_types, frequency,
    schedule_config, timeframe, folder settings, and next/last run.
    """
    try:
        return await api.get_schedule(schedule_id)
    except ApiError as e:
        return _err(e)


@mcp.tool(annotations={"readOnlyHint": True})
async def list_jobs(
    client_id: str | None = None,
    status: str | None = None,
    schedule_id: str | None = None,
    execution_date: str | None = None,
    limit: int = 50,
) -> list[dict] | dict:
    """List report jobs with optional filters.

    Jobs track individual report downloads through stages:
    pending -> requesting -> polling -> downloading -> uploading -> completed.
    Failed jobs show error_details with phase and message.

    Args:
        client_id: Filter by client.
        status: One of pending/requesting/polling/downloading/uploading/completed/failed.
        schedule_id: Filter by originating schedule.
        execution_date: YYYY-MM-DD filter.
        limit: Max results, 1-200 (default 50).
    """
    try:
        return await api.list_jobs(
            client_id=client_id,
            status=status,
            schedule_id=schedule_id,
            execution_date=execution_date,
            limit=limit,
        )
    except ApiError as e:
        return _err(e)


@mcp.tool(annotations={"readOnlyHint": True})
async def get_job(job_id: str) -> dict:
    """Get full details of a specific job.

    Includes status, report type, marketplace, dates, Amazon report ID,
    Google Drive file path (gdrive_path), and error details if failed.
    """
    try:
        return await api.get_job(job_id)
    except ApiError as e:
        return _err(e)


@mcp.tool(annotations={"readOnlyHint": True})
async def list_report_types(api_source: str | None = None) -> dict:
    """Get available report types, organized by API source and category.

    Each entry has id, label, api, category, and optional constraint notes.
    Use this to discover valid report_type IDs for create_schedule or
    request_report.

    Args:
        api_source: Filter to 'sp_api' or 'ads_api'. Omit for all.
    """
    result: dict = {}
    if api_source in (None, "sp_api", "both"):
        result["sp_api"] = SP_REPORT_TYPES
    if api_source in (None, "ads_api", "both"):
        result["ads_api"] = ADS_REPORT_TYPES
    result["marketplaces"] = MARKETPLACES
    return result


@mcp.tool(annotations={"readOnlyHint": True})
async def list_ads_profiles() -> list[dict] | dict:
    """List all Amazon Ads profiles visible to the shared app credentials.

    Returns every advertising profile (profileId, countryCode, accountInfo,
    dailyBudget, timezone, etc.) associated with the authorized Ads API app.
    Profiles already linked to a Kalilos client include _linked_client_id.
    No parameters required — uses the single shared set of Ads API credentials.
    """
    try:
        return await api.list_ads_profiles()
    except ApiError as e:
        return _err(e)


@mcp.tool(annotations={"readOnlyHint": True})
async def get_ads_report_config(report_type: str) -> dict:
    """Get default columns and dimensions for an Ads API report type.

    Returns adProduct, groupBy, available columns (dimensions + metrics),
    and supported time units.
    """
    try:
        return await api.get_ads_report_config(report_type)
    except ApiError as e:
        return _err(e)


# ── Write tools ─────────────────────────────────────────────────────────


@mcp.tool(annotations={"readOnlyHint": False, "idempotentHint": False})
async def create_schedule(
    api_source: str,
    report_types: list[str],
    client_ids: list[str],
    marketplaces: list[str],
    frequency: str = "daily",
    name: str = "",
    timeframe_strategy: str = "yesterday",
    timeframe_days: int | None = None,
    timeframe_days_before: int | None = None,
    timeframe_days_after: int | None = None,
    timeframe_years_back: int | None = None,
    timeframe_anchor_offset_days: int | None = None,
    folder_name: str = "",
    subfolder_strategy: str = "date",
    reconciliation_days: list[int] | None = None,
) -> dict:
    """Create a new recurring report schedule.

    The scheduler fans out one workflow per (client, marketplace, report_type).
    Use list_report_types and list_clients first to discover valid IDs.

    Args:
        api_source: 'sp_api', 'ads_api', or 'both'.
        report_types: Report type IDs to download.
        client_ids: Client IDs to include.
        marketplaces: Marketplace codes (e.g. ['US', 'CA']).
        frequency: 'hourly', 'daily', 'weekly', or 'monthly'.
        name: Display name.
        timeframe_strategy: Date strategy — yesterday, today, last_n_days,
            rolling_window, last_calendar_week, last_calendar_month,
            prior_year_window.
        timeframe_days: Trailing days for last_n_days strategy.
        timeframe_days_before: Days before anchor for prior_year_window.
        timeframe_days_after: Days after anchor for prior_year_window.
        timeframe_years_back: Years to shift back for prior_year_window (default 1).
        timeframe_anchor_offset_days: Shift anchor back N days for data delay (prior_year_window).
        folder_name: Custom Google Drive folder prefix.
        subfolder_strategy: 'date' for YYYY-MM-DD subfolders, 'none' for flat.
        reconciliation_days: Days to re-pull (e.g. [3,7]). Yesterday strategy only.
    """
    data: dict = {
        "api_source": api_source,
        "report_types": report_types,
        "client_ids": client_ids,
        "marketplaces": marketplaces,
        "frequency": frequency,
        "name": name,
        "folder_name": folder_name,
        "subfolder_strategy": subfolder_strategy,
    }
    timeframe: dict = {"strategy": timeframe_strategy}
    if timeframe_strategy == "last_n_days" and timeframe_days is not None:
        timeframe["days"] = timeframe_days
    if timeframe_strategy == "prior_year_window":
        if timeframe_days_before is not None:
            timeframe["days_before"] = timeframe_days_before
        if timeframe_days_after is not None:
            timeframe["days_after"] = timeframe_days_after
        if timeframe_years_back is not None:
            timeframe["years_back"] = timeframe_years_back
        if timeframe_anchor_offset_days is not None:
            timeframe["anchor_offset_days"] = timeframe_anchor_offset_days
    data["timeframe"] = timeframe
    if reconciliation_days is not None:
        data["reconciliation_days"] = reconciliation_days

    try:
        return await api.create_schedule(data)
    except ApiError as e:
        return _err(e)


@mcp.tool(annotations={"readOnlyHint": False, "idempotentHint": True})
async def update_schedule(
    schedule_id: str,
    name: str | None = None,
    is_active: bool | None = None,
    frequency: str | None = None,
    api_source: str | None = None,
    report_types: list[str] | None = None,
    client_ids: list[str] | None = None,
    marketplaces: list[str] | None = None,
    folder_name: str | None = None,
    subfolder_strategy: str | None = None,
) -> dict:
    """Update an existing schedule (partial update — only provided fields change).

    Use get_schedule first to see current values.
    """
    fields: dict = {}
    for key, val in [
        ("name", name), ("is_active", is_active), ("frequency", frequency),
        ("api_source", api_source), ("report_types", report_types),
        ("client_ids", client_ids), ("marketplaces", marketplaces),
        ("folder_name", folder_name), ("subfolder_strategy", subfolder_strategy),
    ]:
        if val is not None:
            fields[key] = val

    if not fields:
        return {"error": True, "message": "No fields provided to update"}

    try:
        return await api.update_schedule(schedule_id, fields)
    except ApiError as e:
        return _err(e)


@mcp.tool(annotations={"readOnlyHint": False, "destructiveHint": True, "idempotentHint": True})
async def delete_schedule(schedule_id: str) -> dict:
    """Delete a schedule permanently. Already-running jobs are not affected."""
    try:
        return await api.delete_schedule(schedule_id)
    except ApiError as e:
        return _err(e)


@mcp.tool(annotations={"readOnlyHint": False, "idempotentHint": False, "openWorldHint": True})
async def trigger_schedule(schedule_id: str) -> dict:
    """Immediately trigger all jobs for a schedule (Run Now).

    Launches workflows for every (client, marketplace, report_type) combo.
    Clients without credentials are silently skipped. Returns job_ids.
    Use list_jobs with the schedule_id afterwards to monitor progress.
    """
    try:
        return await api.trigger_schedule(schedule_id)
    except ApiError as e:
        return _err(e)


@mcp.tool(annotations={"readOnlyHint": False, "idempotentHint": False, "openWorldHint": True})
async def request_report(
    client_id: str,
    api_source: str,
    marketplace: str,
    report_types: list[str],
    start_date: str,
    end_date: str,
    folder_name: str = "",
    subfolder_strategy: str = "date",
) -> dict:
    """Request an on-demand report download for a specific date range.

    Each report_type gets its own workflow. Date range cannot exceed 60 days.
    Use list_report_types to find valid IDs, list_clients for client IDs.

    Args:
        client_id: Amazon seller client ID.
        api_source: 'sp_api', 'ads_api', or 'both'.
        marketplace: Single marketplace code (e.g. 'US').
        report_types: Report type IDs.
        start_date: YYYY-MM-DD.
        end_date: YYYY-MM-DD.
        folder_name: Custom Drive folder prefix.
        subfolder_strategy: 'date' or 'none'.
    """
    try:
        return await api.request_on_demand({
            "client_id": client_id,
            "api_source": api_source,
            "marketplace": marketplace,
            "report_types": report_types,
            "start_date": start_date,
            "end_date": end_date,
            "folder_name": folder_name,
            "subfolder_strategy": subfolder_strategy,
        })
    except ApiError as e:
        return _err(e)


@mcp.tool(annotations={"readOnlyHint": False, "idempotentHint": False, "openWorldHint": True})
async def retry_job(job_id: str) -> dict:
    """Retry a failed job with the same parameters.

    Creates a new job and workflow execution. Only works on failed jobs.
    Returns the new job_id.
    """
    try:
        return await api.retry_job(job_id)
    except ApiError as e:
        return _err(e)


# ── ASGI app (for Cloud Run / uvicorn) ──────────────────────────────────

app = mcp.http_app()

# ── CLI entry point ─────────────────────────────────────────────────────


if __name__ == "__main__":
    transport = os.environ.get("MCP_TRANSPORT", "streamable-http")
    if transport == "stdio":
        mcp.run(transport="stdio")
    else:
        port = int(os.environ.get("PORT", "8080"))
        mcp.run(transport="streamable-http", host="0.0.0.0", port=port)
