/**
 * Report type categorization, descriptions, and constraints.
 *
 * Used by the report selector dropdown to group reports by domain
 * and surface helpful context to users.
 */

export interface ReportTypeInfo {
  id: string;
  label: string;
  description: string;
  constraint?: string;
}

export interface ReportCategory {
  label: string;
  reports: ReportTypeInfo[];
}

export const SP_REPORT_CATEGORIES: ReportCategory[] = [
  {
    label: "Listings",
    reports: [
      {
        id: "GET_FLAT_FILE_OPEN_LISTINGS_DATA",
        label: "Open Listings",
        description: "Active listings with price, quantity, and condition",
      },
      {
        id: "GET_MERCHANT_LISTINGS_ALL_DATA",
        label: "All Listings",
        description: "All listings including inactive, with full details",
      },
    ],
  },
  {
    label: "Orders & Shipments",
    reports: [
      {
        id: "GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL",
        label: "Orders (by Order Date)",
        description: "All orders sorted by order date",
      },
      {
        id: "GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL",
        label: "Orders (by Last Update)",
        description: "All orders sorted by last update date",
      },
      {
        id: "GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL",
        label: "Amazon Fulfilled Shipments",
        description: "FBA shipment details with tracking and item info",
      },
    ],
  },
  {
    label: "FBA Inventory",
    reports: [
      {
        id: "GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA",
        label: "FBA Inventory (Unsuppressed)",
        description: "FBA inventory levels for active items",
      },
      {
        id: "GET_AFN_INVENTORY_DATA",
        label: "AFN Inventory",
        description: "Amazon Fulfillment Network inventory snapshot",
      },
      {
        id: "GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA",
        label: "FBA Estimated Fees",
        description: "Estimated FBA fees per product",
      },
    ],
  },
  {
    label: "Returns & Removals",
    reports: [
      {
        id: "GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE",
        label: "FBM Returns",
        description: "Merchant-fulfilled returns by return date",
      },
      {
        id: "GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA",
        label: "FBA Returns",
        description: "FBA customer returns with reason and disposition",
      },
      {
        id: "GET_FBA_FULFILLMENT_REMOVAL_SHIPMENT_DETAIL_DATA",
        label: "Removal Shipment Detail",
        description: "FBA removal shipments (returns to seller or disposal)",
        constraint: "Only available when the account has removal orders",
      },
    ],
  },
  {
    label: "Financial",
    reports: [
      {
        id: "GET_LEDGER_SUMMARY_VIEW_DATA",
        label: "Ledger Summary",
        description: "Financial ledger summary by ASIN",
      },
      {
        id: "GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2",
        label: "Settlement Report",
        description: "Settlement report with transaction details",
        constraint: "Auto-generated by Amazon \u2014 cannot be requested on demand. Use the Reports list in Seller Central instead.",
      },
    ],
  },
  {
    label: "Sales & Traffic",
    reports: [
      {
        id: "GET_SALES_AND_TRAFFIC_REPORT",
        label: "Sales & Traffic",
        description: "Sales and traffic metrics per ASIN (Brand Analytics)",
        constraint: "Requires Brand Registry. Supports dateGranularity: Day / Week / Month.",
      },
    ],
  },
  {
    label: "Brand Analytics",
    reports: [
      {
        id: "GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT",
        label: "Search Terms",
        description: "Top search terms with click and conversion share",
        constraint: "Requires Brand Registry. Use \"Yesterday\" timeframe for daily, or \"Last Calendar Month\" for monthly.",
      },
      {
        id: "GET_BRAND_ANALYTICS_MARKET_BASKET_REPORT",
        label: "Market Basket",
        description: "Products frequently bought together",
        constraint: "Requires Brand Registry and \"Last Calendar Week\" or \"Last Calendar Month\" timeframe (daily not supported).",
      },
      {
        id: "GET_BRAND_ANALYTICS_REPEAT_PURCHASE_REPORT",
        label: "Repeat Purchase",
        description: "Customer repeat purchase behavior by ASIN",
        constraint: "Requires Brand Registry and \"Last Calendar Week\" or \"Last Calendar Month\" timeframe (daily not supported).",
      },
      {
        id: "GET_BRAND_ANALYTICS_SEARCH_QUERY_PERFORMANCE_REPORT",
        label: "Search Query Performance",
        description: "Impressions, clicks, cart adds, and purchases per query per ASIN",
        constraint: "Requires Brand Registry and \"Last Calendar Week\" or \"Last Calendar Month\" timeframe. ASINs must be configured in report options.",
      },
      {
        id: "GET_BRAND_ANALYTICS_SEARCH_CATALOG_PERFORMANCE_REPORT",
        label: "Search Catalog Performance",
        description: "Aggregate search funnel metrics per ASIN across all queries",
        constraint: "Requires Brand Registry and \"Last Calendar Week\" or \"Last Calendar Month\" timeframe.",
      },
    ],
  },
];

export const ADS_REPORT_CATEGORIES: ReportCategory[] = [
  {
    label: "Sponsored Products",
    reports: [
      {
        id: "spCampaigns",
        label: "SP \u2014 Campaigns",
        description: "Campaign-level spend, clicks, and sales",
      },
      {
        id: "spSearchTerm",
        label: "SP \u2014 Search Term",
        description: "Search term performance with keyword targeting",
      },
      {
        id: "spTargeting",
        label: "SP \u2014 Targeting",
        description: "Targeting-level performance metrics",
      },
      {
        id: "spAdvertisedProduct",
        label: "SP \u2014 Advertised Product",
        description: "ASIN-level performance for Sponsored Products",
      },
    ],
  },
  {
    label: "Sponsored Brands",
    reports: [
      {
        id: "sbCampaigns",
        label: "SB \u2014 Campaigns",
        description: "Campaign-level performance for Sponsored Brands",
      },
      {
        id: "sbSearchTerm",
        label: "SB \u2014 Search Term",
        description: "Search term performance for Sponsored Brands",
      },
    ],
  },
  {
    label: "Sponsored Display",
    reports: [
      {
        id: "sdCampaigns",
        label: "SD \u2014 Campaigns",
        description: "Campaign-level performance for Sponsored Display",
      },
      {
        id: "sdTargeting",
        label: "SD \u2014 Targeting",
        description: "Targeting-level performance for Sponsored Display",
      },
      {
        id: "sdAdvertisedProduct",
        label: "SD \u2014 Advertised Product",
        description: "ASIN-level performance for Sponsored Display",
      },
    ],
  },
];

export function flattenCategories(categories: ReportCategory[]): ReportTypeInfo[] {
  return categories.flatMap((c) => c.reports);
}

export function getReportInfo(id: string): ReportTypeInfo | undefined {
  for (const cat of [...SP_REPORT_CATEGORIES, ...ADS_REPORT_CATEGORIES]) {
    const found = cat.reports.find((r) => r.id === id);
    if (found) return found;
  }
  return undefined;
}
