/**
 * Report type categorization, descriptions, and constraints.
 *
 * Used by the report selector dropdown to group reports by domain
 * and surface helpful context to users.
 */

export interface ReportTypeInfo {
  id: string;
  label: string;
  description: string;
  constraint?: string;
}

export interface ReportCategory {
  label: string;
  reports: ReportTypeInfo[];
}

export const SP_REPORT_CATEGORIES: ReportCategory[] = [
  {
    label: "Listings",
    reports: [
      {
        id: "GET_FLAT_FILE_OPEN_LISTINGS_DATA",
        label: "Open Listings",
        description: "Active listings with price, quantity, and condition",
      },
      {
        id: "GET_MERCHANT_LISTINGS_ALL_DATA",
        label: "All Listings",
        description: "All listings including inactive, with full details",
      },
    ],
  },
  {
    label: "Orders & Shipments",
    reports: [
      {
        id: "GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL",
        label: "Orders (by Order Date)",
        description: "All orders sorted by order date",
      },
      {
        id: "GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL",
        label: "Orders (by Last Update)",
        description: "All orders sorted by last update date",
      },
      {
        id: "GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL",
        label: "Amazon Fulfilled Shipments",
        description: "FBA shipment details with tracking and item info",
      },
    ],
  },
  {
    label: "Inventory",
    reports: [
      {
        id: "GET_MERCHANT_LISTINGS_DATA",
        label: "FBM Inventory (Active Listings)",
        description: "Active merchant-fulfilled listings with SKU, price, quantity, and fulfillment channel",
      },
      {
        id: "GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA",
        label: "FBA Inventory (Unsuppressed)",
        description: "FBA inventory levels for active items",
      },
      {
        id: "GET_AFN_INVENTORY_DATA",
        label: "AFN Inventory",
        description: "Amazon Fulfillment Network inventory snapshot",
      },
      {
        id: "GET_FBA_MYI_ALL_INVENTORY_DATA",
        label: "Manage FBA Inventory (All)",
        description: "All FBA inventory including suppressed/archived items with condition, quantity, and volume",
      },
      {
        id: "GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA",
        label: "FBA Estimated Fees",
        description: "Estimated FBA fees per product",
      },
      {
        id: "GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT",
        label: "Restock Inventory",
        description: "Restock recommendations with suggested order quantities and reorder dates",
        constraint: "Being phased out from Seller Central in favor of FBA Inventory Planning. Still available via SP API.",
      },
      {
        id: "GET_STRANDED_INVENTORY_UI_DATA",
        label: "Stranded Inventory",
        description: "Inventory in stranded status with reason and recommended actions",
      },
      {
        id: "GET_FBA_INVENTORY_PLANNING_DATA",
        label: "FBA Inventory (Health)",
        description: "Consolidated inventory health: sales velocity (7/30/60/90d), storage fees, aging, excess units, and restock recommendations",
        constraint: "Not available in NL, PL, SE, or BE marketplaces.",
      },
    ],
  },
  {
    label: "Subscribe & Save",
    reports: [
      {
        id: "GET_FBA_SNS_PERFORMANCE_DATA",
        label: "Subscribe & Save Performance",
        description: "Weekly S&S performance: units shipped, sale price, discounts, and out-of-stock rate",
        constraint: "Deprecated by Amazon (Dec 2025). Requests may return CANCELLED/FATAL. Weekly timeframe only (Saturday\u2013Monday window).",
      },
    ],
  },
  {
    label: "Returns & Removals",
    reports: [
      {
        id: "GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE",
        label: "FBM Returns",
        description: "Merchant-fulfilled returns by return date",
      },
      {
        id: "GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA",
        label: "FBA Returns",
        description: "FBA customer returns with reason and disposition",
      },
      {
        id: "GET_FBA_FULFILLMENT_REMOVAL_SHIPMENT_DETAIL_DATA",
        label: "Removal Shipment Detail",
        description: "FBA removal shipments (returns to seller or disposal)",
        constraint: "Only available when the account has removal orders",
      },
    ],
  },
  {
    label: "Financial",
    reports: [
      {
        id: "GET_LEDGER_SUMMARY_VIEW_DATA",
        label: "Ledger Summary",
        description: "Financial ledger summary by ASIN",
      },
      {
        id: "GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2",
        label: "Settlement Report",
        description: "Settlement report with transaction details",
        constraint: "Auto-generated by Amazon \u2014 cannot be requested on demand. Use the Reports list in Seller Central instead.",
      },
    ],
  },
  {
    label: "Sales & Traffic",
    reports: [
      {
        id: "GET_SALES_AND_TRAFFIC_REPORT",
        label: "Sales & Traffic",
        description: "Sales and traffic metrics per ASIN (Brand Analytics)",
        constraint: "Requires Brand Registry. Supports dateGranularity: Day / Week / Month.",
      },
    ],
  },
  {
    label: "Brand Analytics",
    reports: [
      {
        id: "GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT",
        label: "Search Terms",
        description: "Top search terms with click and conversion share",
        constraint: "Requires Brand Registry. Use \"Yesterday\" timeframe for daily, or \"Last Calendar Month\" for monthly.",
      },
      {
        id: "GET_BRAND_ANALYTICS_MARKET_BASKET_REPORT",
        label: "Market Basket",
        description: "Products frequently bought together",
        constraint: "Requires Brand Registry and \"Last Calendar Week\" or \"Last Calendar Month\" timeframe (daily not supported).",
      },
      {
        id: "GET_BRAND_ANALYTICS_REPEAT_PURCHASE_REPORT",
        label: "Repeat Purchase",
        description: "Customer repeat purchase behavior by ASIN",
        constraint: "Requires Brand Registry and \"Last Calendar Week\" or \"Last Calendar Month\" timeframe (daily not supported).",
      },
      {
        id: "GET_BRAND_ANALYTICS_SEARCH_QUERY_PERFORMANCE_REPORT",
        label: "Search Query Performance",
        description: "Impressions, clicks, cart adds, and purchases per query per ASIN",
        constraint: "Requires Brand Registry and \"Last Calendar Week\" or \"Last Calendar Month\" timeframe. ASINs must be configured in report options.",
      },
      {
        id: "GET_BRAND_ANALYTICS_SEARCH_CATALOG_PERFORMANCE_REPORT",
        label: "Search Catalog Performance",
        description: "Aggregate search funnel metrics per ASIN across all queries",
        constraint: "Requires Brand Registry and \"Last Calendar Week\" or \"Last Calendar Month\" timeframe.",
      },
    ],
  },
  {
    label: "Vendor (1P)",
    reports: [
      {
        id: "GET_VENDOR_SALES_REPORT",
        label: "Vendor Sales",
        description: "Vendor sales by ASIN: ordered (purchase-order demand) and shipped revenue/units",
        constraint: "Vendor Central (1P) accounts only. Use distributorView SOURCING and/or MANUFACTURING for both views.",
      },
      {
        id: "GET_VENDOR_TRAFFIC_REPORT",
        label: "Vendor Traffic (ARA)",
        description: "Vendor ARA traffic & conversion: glance views and conversion metrics per ASIN",
        constraint: "Vendor Central (1P) accounts only.",
      },
      {
        id: "GET_VENDOR_INVENTORY_REPORT",
        label: "Vendor Inventory Health",
        description: "Vendor inventory health: sellable/unsellable on-hand, aged inventory, and net received units",
        constraint: "Vendor Central (1P) accounts only. Use distributorView SOURCING and/or MANUFACTURING for both views.",
      },
    ],
  },
];

export const ADS_REPORT_CATEGORIES: ReportCategory[] = [
  {
    label: "Sponsored Products",
    reports: [
      {
        id: "spCampaigns",
        label: "SP \u2014 Campaigns",
        description: "Campaign-level metrics: campaignName, status, budget, impressions, clicks, cost, purchases (1/7/14/30d), sales (1/7/14/30d)",
      },
      {
        id: "spSearchTerm",
        label: "SP \u2014 Search Term",
        description: "Search term performance: searchTerm, targeting, keywordId, keywordType, impressions, clicks, cost, purchases, sales",
      },
      {
        id: "spTargeting",
        label: "SP \u2014 Targeting",
        description: "Keyword/targeting performance: targeting, keyword, keywordId, keywordType, matchType, impressions, clicks, cost, purchases, sales",
      },
      {
        id: "spAdvertisedProduct",
        label: "SP \u2014 Advertised Product",
        description: "ASIN-level performance: advertisedAsin, advertisedSku, impressions, clicks, cost, purchases, sales per ad group",
      },
      {
        id: "spPlacement",
        label: "SP \u2014 Placement",
        description: "Placement performance: top of search, product pages, and other placements with impressions, clicks, cost, purchases, sales (1/7/14/30d)",
      },
    ],
  },
  {
    label: "Sponsored Brands",
    reports: [
      {
        id: "sbCampaigns",
        label: "SB \u2014 Campaigns",
        description: "Campaign-level metrics: campaignName, status, budget, impressions, clicks, cost, purchases, sales, detailPageViews, newToBrand",
        constraint: "v3 reporting only returns Sponsored Brands v4 (multi-ad-group) campaigns. Legacy SB campaigns are omitted by Amazon, so totals can be lower than the Ads console \u201CAll but archived\u201D view.",
      },
      {
        id: "sbSearchTerm",
        label: "SB \u2014 Search Term",
        description: "Search term performance: searchTerm, campaignName, adGroupName, impressions, clicks, cost, purchases, sales",
        constraint: "v3 reporting only returns Sponsored Brands v4 (multi-ad-group) campaigns. Legacy SB campaign search terms are omitted by Amazon.",
      },
    ],
  },
  {
    label: "Sponsored Display",
    reports: [
      {
        id: "sdCampaigns",
        label: "SD \u2014 Campaigns",
        description: "Campaign-level metrics: campaignName, status, budget, impressions, clicks, cost, purchases, sales, detailPageViews, newToBrand",
      },
      {
        id: "sdTargeting",
        label: "SD \u2014 Targeting",
        description: "Targeting performance: targetingText, impressions, clicks, cost, purchases, sales, detailPageViews, newToBrand",
      },
      {
        id: "sdAdvertisedProduct",
        label: "SD \u2014 Advertised Product",
        description: "ASIN-level performance: promotedAsin, promotedSku, impressions, clicks, cost, purchases, sales, detailPageViews, newToBrand",
      },
    ],
  },
];

export function flattenCategories(categories: ReportCategory[]): ReportTypeInfo[] {
  return categories.flatMap((c) => c.reports);
}

export function getReportInfo(id: string): ReportTypeInfo | undefined {
  for (const cat of [...SP_REPORT_CATEGORIES, ...ADS_REPORT_CATEGORIES]) {
    const found = cat.reports.find((r) => r.id === id);
    if (found) return found;
  }
  return undefined;
}
